name: C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Generate release version
      id: release_version
      run: |
        echo "VERSION=$(date +'%Y.%m.%d-%H%M')" >> $GITHUB_OUTPUT
      
    - name: Create Release
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: release-${{ steps.release_version.outputs.VERSION }}
        name: Release ${{ steps.release_version.outputs.VERSION }}
        draft: false
        prerelease: false
        files: |
          bin/client.exec
          install/install.sh
          install/uninstall.sh
          install/system-monitor.service
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}